import { Component, OnInit } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { Game } from 'src/app/shared/models/games.model';

@Component({
  selector: 'app-ofertas',
  templateUrl: './ofertas.component.html',
  styleUrls: ['./ofertas.component.css', './ofertas.responsive.component.css']
})
export class OfertasComponent implements OnInit {
  quantidadeItens!: number;
  gamesData: Game[] = [
    {
      img: '../../../assets/dead-space.jpg',
      altImg: 'Capa do game Dead Space',
      plataforma: ['PS5'],
      produtoType: '',
      title: 'Dead Space',
      produtoBloco: '',
      porcentagem: '-40%',
      precoAtual: 'R$ 203,34',
      precoAnterior: 'R$ 338,90',
    },
    {
      img: '../../../assets/destiny-2-anual.jpg',
      altImg: 'Capa do game Destiny 2: A queda da luz + Passe Anual',
      plataforma: ['PS5', 'PS4'],
      produtoType: 'Pacote de expansões',
      title: 'Destiny 2: A queda da luz + Passe Anual',
      produtoBloco: '',
      porcentagem: '-50%',
      precoAtual: 'R$ 189,99',
      precoAnterior: 'R$ 379,99',
    },
    {
      img: '../../../assets/destiny-2.jpg',
      altImg: 'Capa do game Destiny 2: A queda da luz',
      plataforma: ['PS5', 'PS4'],
      produtoType: 'Pacote de expansões',
      title: 'Destiny 2: A queda da luz',
      produtoBloco: '',
      porcentagem: '-50%',
      precoAtual: 'R$ 94,99',
      precoAnterior: 'R$ 189,99',
    },
    {
      img: '../../../assets/f1-23.jpg',
      altImg: 'Capa do game F1 23',
      plataforma: ['PS5', 'PS4'],
      produtoType: 'Pacote de expansões',
      title: 'Destiny 2: A queda da luz',
      produtoBloco: '',
      porcentagem: '-50%',
      precoAtual: 'R$ 94,99',
      precoAnterior: 'R$ 189,99',
    },
    {
      img: '../../../assets/gta-moedas-ps4.jpg',
      altImg: 'Capa do pacote de moedas do GTA',
      plataforma: [],
      produtoType: 'MOEDA VIRTUAL',
      title: 'GTA Online: Pacote de Dinheiro Megalodonte (PS4&#170;)',
      produtoBloco: '',
      porcentagem: '-15%',
      precoAtual: 'R$4S4,66',
      precoAnterior: 'R$ 534,90',
    },
    {
      img: '../../../assets/gta-v.jpg',
      altImg: 'Capa do game GTA edição premium',
      plataforma: ['PS4'],
      title: 'Grand Theft Auto V: Edição Premium',
      produtoBloco: '',
      porcentagem: '-33%',
      precoAtual: 'R$107,13',
      precoAnterior: 'R$ 159,90',
    },
    {
      img: '../../../assets/hogwarts.jpg',
      altImg: 'Capa do game Hogwarts Legacy Versão PS5',
      plataforma: ['PS5'],
      title: 'Hogwarts Legacy Versão PS5',
      produtoBloco: 'Deluxe',
      porcentagem: '-30%',
      precoAtual: 'R$209,93',
      precoAnterior: 'R$ 299,90',
    },
    {
      img: '../../../assets/madden-nfl.jpg',
      altImg: 'Capa do game Madden NFL 24',
      plataforma: ['PS5', 'PS4'],
      produtoType: '',
      title: 'Madden NFL 24',
      produtoBloco: 'Experimentação do jogo',
      porcentagem: '-35%',
      precoAtual: 'R$ 223,28',
      precoAnterior: 'R$ 358,90',
    },
    {
      img: '../../../assets/pga.jpg',
      altImg: 'Capa do game PGA TOUR 2K23',
      plataforma: ['PS4'],
      produtoType: '',
      title: 'PGA TOUR 2K23',
      produtoBloco: '',
      porcentagem: '-67%',
      precoAtual: 'R$ 98,96',
      precoAnterior: 'R$ 299,90',
    },
    {
      img: '../../../assets/red-dead.jpg',
      altImg: 'Capa do game Red Dead Redemption 2',
      plataforma: ['PS4'],
      produtoType: '',
      title: 'Red Dead Redemption 2',
      produtoBloco: '',
      porcentagem: '-67%',
      precoAtual: 'R$ 82,13',
      precoAnterior: 'R$ 248,90',
    },
    {
      img: '../../../assets/remnant.jpg',
      altImg: 'Capa do game Remnant II - Deluxe Edition',
      plataforma: ['PS5'],
      produtoType: 'Pacote do jogo',
      title: 'Remnant II - Deluxe Edition',
      produtoBloco: '',
      porcentagem: '-20%',
      precoAtual: 'R$ 239,92',
      precoAnterior: 'R$ 299,90',
    },
    {
      img: '../../../assets/star-wars.jpg',
      altImg: 'Capa do game STAR WARS Jedi: Survivor',
      plataforma: ['PS5'],
      produtoType: '',
      title: 'STAR WARS Jedi: Survivor&#170;',
      produtoBloco: '',
      porcentagem: '-35%',
      precoAtual: 'R$ 220,28',
      precoAnterior: 'R$ 338,90',
    },
    {
      img: '../../../assets/the-crew-cross-gen.jpg',
      altImg: 'Capa do game The Crew Motorfest Pacote Cross-Gen',
      plataforma: ['PS5', 'PS4'],
      produtoType: '',
      title: 'The Crew&#170; Motorfest Pacote Cross-Gen ',
      produtoBloco: '',
      porcentagem: '-20%',
      precoAtual: 'R$ 263,92',
      precoAnterior: 'R$ 329,90',
    },
    {
      img: '../../../assets/f1-23.jpg',
      altImg: 'Capa do game F1 23',
      plataforma: ['PS5', 'PS4'],
      produtoType: 'Pacote de expansões',
      title: 'Destiny 2: A queda da luz',
      produtoBloco: '',
      porcentagem: '-50%',
      precoAtual: 'R$ 94,99',
      precoAnterior: 'R$ 189,99',
    },
    {
      img: '../../../assets/gta-moedas-ps4.jpg',
      altImg: 'Capa do pacote de moedas do GTA',
      plataforma: [],
      produtoType: 'MOEDA VIRTUAL',
      title: 'GTA Online: Pacote de Dinheiro Megalodonte (PS4&#170;)',
      produtoBloco: '',
      porcentagem: '-15%',
      precoAtual: 'R$4S4,66',
      precoAnterior: 'R$ 534,90',
    },
    {
      img: '../../../assets/dead-space.jpg',
      altImg: 'Capa do game Dead Space',
      plataforma: ['PS5'],
      produtoType: '',
      title: 'Dead Space',
      produtoBloco: '',
      porcentagem: '-40%',
      precoAtual: 'R$ 203,34',
      precoAnterior: 'R$ 338,90',
    },
  ];

  constructor(private serviceTitle: Title) { }

  ngOnInit(): void {
    this.serviceTitle.setTitle('Ofertas | PlayStation Store');
    this.quantidadeItens = this.gamesData.length;
    console.log(this.quantidadeItens);
  }

}
